# Generated by Django 3.2.3 on 2021-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
